from typing import Protocol


class LcdHatDriver(Protocol):
    def init(self) -> None: ...
    def clear(self, screen_id: str) -> None: ...
    def draw_image(self, screen_id: str, image: object) -> None: ...
    def set_backlight(self, screen_id: str, enabled: bool) -> None: ...
    def close(self) -> None: ...
